"""Site generator tests.

The published site is the deliverable a reviewer actually reads, and it is
generated by a small hand-written markdown converter.  A converter that silently
mangles a table would publish a wrong number in a page that looks authoritative,
so the converter is tested directly rather than by eyeballing the output.
"""
import html, os, pathlib, re, subprocess, sys, time, unittest
import helpers  # noqa: F401
sys.path.insert(0, helpers.REPO)
sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))

import build_site

SITE = pathlib.Path(helpers.REPO) / "site"
DOCS = pathlib.Path(helpers.REPO) / "docs"


class TestInlineMarkup(unittest.TestCase):
    def test_plain_text_passes_through(self):
        self.assertEqual(build_site._inline("hello world"), "hello world")

    def test_html_is_escaped_before_markup_is_applied(self):
        """An endpoint note can contain angle brackets; rendering it raw would
        inject markup into a published page."""
        out = build_site._inline("a <script>alert(1)</script> b")
        self.assertNotIn("<script>", out)
        self.assertIn("&lt;script&gt;", out)

    def test_bold_and_code(self):
        self.assertEqual(build_site._inline("**x**"), "<strong>x</strong>")
        self.assertEqual(build_site._inline("`y`"), "<code>y</code>")

    def test_code_contents_are_never_reinterpreted(self):
        out = build_site._inline("`**not bold**`")
        self.assertEqual(out, "<code>**not bold**</code>")

    def test_external_links_open_safely(self):
        out = build_site._inline("[MLB](https://statsapi.mlb.com/)")
        self.assertIn('href="https://statsapi.mlb.com/"', out)
        self.assertIn('target="_blank"', out)
        self.assertIn('rel="noopener noreferrer"', out)

    def test_relative_markdown_links_become_html_links(self):
        out = build_site._inline("[next](02-data-sources.md)")
        self.assertIn('href="02-data-sources.html"', out)
        self.assertNotIn("target=", out, "internal links must not open a new tab")

    def test_fragment_links_are_preserved(self):
        self.assertIn('href="#ir-05"', build_site._inline("[IR-05](#ir-05)"))

    def test_a_url_with_query_string_survives(self):
        out = build_site._inline("[grid](https://rotogrinders.com/projected-stats/mlb?site=draftkings)")
        self.assertIn("site=draftkings", out)

    def test_italics_do_not_eat_bold(self):
        out = build_site._inline("**bold** and *italic*")
        self.assertIn("<strong>bold</strong>", out)
        self.assertIn("<em>italic</em>", out)

    def test_a_pipe_inside_a_link_label_does_not_break(self):
        self.assertIn("a|b", build_site._inline("[a|b](https://x.example/)"))


class TestTables(unittest.TestCase):
    def test_a_two_column_table_renders_head_and_body(self):
        md = "| a | b |\n| --- | --- |\n| 1 | 2 |\n| 3 | 4 |"
        out, _ = build_site.markdown_to_html(md)
        self.assertIn("<thead><tr><th>a</th><th>b</th></tr></thead>", out)
        self.assertEqual(out.count("<tr>"), 3)
        self.assertIn("<td>4</td>", out)

    def test_alignment_markers_are_honoured(self):
        md = "| l | c | r |\n| :--- | :---: | ---: |\n| 1 | 2 | 3 |"
        out, _ = build_site.markdown_to_html(md)
        self.assertIn('style="text-align:left"', out)
        self.assertIn('style="text-align:center"', out)
        self.assertIn('style="text-align:right"', out)

    def test_an_escaped_pipe_stays_inside_its_cell(self):
        md = "| a | b |\n| --- | --- |\n| x \\| y | z |"
        out, _ = build_site.markdown_to_html(md)
        self.assertIn("<td>x | y</td>", out)
        self.assertEqual(out.count("<td>"), 2, "the escaped pipe must not split the cell")

    def test_a_row_shorter_than_the_header_does_not_crash(self):
        md = "| a | b | c |\n| --- | --- | --- |\n| 1 |"
        out, _ = build_site.markdown_to_html(md)
        self.assertEqual(out.count("<td>"), 3)

    def test_inline_markup_works_inside_cells(self):
        md = "| a |\n| --- |\n| `code` and **bold** |"
        out, _ = build_site.markdown_to_html(md)
        self.assertIn("<td><code>code</code> and <strong>bold</strong></td>", out)

    def test_a_table_is_wrapped_for_horizontal_scrolling(self):
        out, _ = build_site.markdown_to_html("| a |\n| --- |\n| 1 |")
        self.assertIn('<div class="table-wrap">', out)


class TestBlockElements(unittest.TestCase):
    def test_headings_get_ids_and_enter_the_toc(self):
        out, toc = build_site.markdown_to_html("# Title\n\n## A Section\n")
        self.assertIn('<h1 id="title">Title</h1>', out)
        self.assertIn('<h2 id="a-section">A Section</h2>', out)
        self.assertEqual([t["level"] for t in toc], [1, 2])
        self.assertEqual(toc[1]["slug"], "a-section")

    def test_consecutive_blockquote_lines_form_one_quote(self):
        out, _ = build_site.markdown_to_html("> line one\n> line two\n")
        self.assertEqual(out.count("<blockquote>"), 1)
        self.assertIn("line one<br>", out)

    def test_unordered_and_ordered_lists(self):
        out, _ = build_site.markdown_to_html("- a\n- b\n\n1. one\n2. two\n")
        flat = "".join(out.split())
        self.assertIn("<ul><li>a</li><li>b</li></ul>", flat)
        self.assertIn("<ol><li>one</li><li>two</li></ol>", flat)

    def test_supported_nesting_leaves_no_placeholder_or_literal_marker(self):
        """Regression: bold containing code emitted a raw \x00 sentinel."""
        for md in ("**`FPTS/$` is reproduced.**", "[**bold link**](https://x.example/)",
                   "*a `b` c*", "`**x**` and **`y`**"):
            out = build_site._inline(md)
            self.assertNotIn("\x00", out, md)
        # Asterisks inside a code span are CONTENT and must survive verbatim, so
        # the "no literal marker" check strips code spans before asserting.
        for md in ("**`FPTS/$` is reproduced.**", "[**bold link**](https://x.example/)",
                   "*a `b` c*", "`**x**` and **`y`**"):
            out = re.sub(r"<code>.*?</code>", "", build_site._inline(md))
            self.assertNotIn("**", out, md)
            self.assertNotIn("*", out.replace("<em>", "").replace("</em>", ""), md)

    def test_bold_inside_italic_is_a_declared_limitation(self):
        """The subset does not nest bold inside italic; documented, not silently wrong."""
        out = build_site._inline("**a *b* c**")
        self.assertIn("*", out, "this case is unsupported - if it starts working, "
                                "move it into the supported-nesting test above")

    def test_no_committed_document_uses_the_unsupported_nesting(self):
        """The limitation above can only stay harmless while nothing exercises it."""
        pat = re.compile(r"\*\*[^*]*\*[^*]+\*[^*]*\*\*")
        offenders = []
        for path in sorted(DOCS.glob("*.md")) + [pathlib.Path(helpers.REPO) / "README.md"]:
            if not path.exists():
                continue
            for lineno, line in enumerate(path.read_text(encoding="utf-8").split("\n"), 1):
                for m in pat.finditer(line):
                    offenders.append(f"{path.name}:{lineno}: {m.group(0)[:60]}")
        self.assertEqual(offenders, [])

    def test_a_list_switching_type_closes_the_previous_list(self):
        out, _ = build_site.markdown_to_html("- a\n1. one\n")
        self.assertEqual(out.count("<ul>"), 1)
        self.assertEqual(out.count("<ol>"), 1)
        self.assertEqual(out.count("</ul>"), 1)

    def test_fenced_code_is_escaped_and_keeps_newlines(self):
        md = "```python\nif a < b:\n    print('x')\n```\n"
        out, _ = build_site.markdown_to_html(md)
        self.assertIn('<pre><code class="language-python">', out)
        self.assertIn("a &lt; b", out)
        self.assertIn("\n", out)
        self.assertNotIn("<br>", out)

    def test_a_fence_with_no_language(self):
        out, _ = build_site.markdown_to_html("```\nplain\n```\n")
        self.assertIn("<pre><code>plain</code></pre>", out)

    def test_horizontal_rule(self):
        out, _ = build_site.markdown_to_html("a\n\n---\n\nb")
        self.assertIn("<hr>", out)

    def test_paragraphs_are_joined_from_wrapped_source_lines(self):
        out, _ = build_site.markdown_to_html("one\ntwo\n\nthree\n")
        self.assertIn("<p>one two</p>", out)
        self.assertIn("<p>three</p>", out)

    def test_the_generated_banner_is_not_rendered_as_content(self):
        """build_site strips it before conversion; check that it would otherwise
        be harmless rather than appearing as a heading."""
        out, _ = build_site.markdown_to_html("<!-- GENERATED by x -->\n\n# Title\n")
        self.assertIn("<h1", out)

    def test_details_blocks_pass_through(self):
        out, _ = build_site.markdown_to_html("<details><summary>S</summary>\n\n- a\n\n</details>\n")
        self.assertIn("<details>", out)
        self.assertIn("<summary>", out)
        self.assertIn("<ul><li>a</li></ul>", "".join(out.split()))
        self.assertIn("</details>", out)

    def test_an_unterminated_list_at_end_of_input_is_closed(self):
        out, _ = build_site.markdown_to_html("- a\n- b")
        self.assertEqual(out.count("<ul>"), out.count("</ul>"))

    def test_output_is_well_formed_enough_to_parse(self):
        from xml.etree import ElementTree
        md = (DOCS / "00-index.md").read_text(encoding="utf-8")
        body, _ = build_site.markdown_to_html(md)
        wrapped = f"<root>{body}</root>"
        try:
            ElementTree.fromstring(wrapped)
        except ElementTree.ParseError as exc:
            # <br> and <hr> are legal HTML but not XML; normalise before failing.
            normalised = re.sub(r"<(br|hr)>", r"<\1/>", wrapped)
            ElementTree.fromstring(normalised)


class TestGeneratedSite(unittest.TestCase):
    """The committed site/ must match what the generator produces."""

    @classmethod
    def setUpClass(cls):
        cls.result = subprocess.run(
            [sys.executable, str(pathlib.Path(helpers.REPO) / "scripts" / "build_site.py"),
             "--check"],
            cwd=helpers.REPO, capture_output=True, text=True)

    def test_the_site_is_not_stale(self):
        self.assertEqual(self.result.returncode, 0, self.result.stdout + self.result.stderr)

    def test_every_page_exists_and_is_nonempty(self):
        for name in ("index.html", "sources.html", "scoring.html", "findings.html",
                     "rosters.html", "grid.html", "checks.html", "styles.css", "app.js"):
            path = SITE / name
            self.assertTrue(path.exists(), f"{name} was not generated")
            self.assertGreater(path.stat().st_size, 100, name)

    def test_every_documented_page_exists(self):
        for fname, _label in build_site.DOC_ORDER:
            target = fname[:-3] + ".html"
            self.assertTrue((SITE / target).exists(), target)
            self.assertTrue((DOCS / fname).exists(), fname)

    def test_pages_carry_the_shared_layout(self):
        text = (SITE / "index.html").read_text(encoding="utf-8")
        self.assertIn("<!DOCTYPE html>", text)
        self.assertIn('lang="en"', text)
        self.assertIn('<meta charset="utf-8">', text)
        self.assertIn('name="viewport"', text)
        self.assertIn('href="styles.css"', text)
        self.assertIn('<a class="skip" href="#main">Skip to content</a>', text)

    def test_no_page_depends_on_a_cdn_or_external_script(self):
        """The site must render with no network access at all."""
        for path in SITE.glob("*.html"):
            text = path.read_text(encoding="utf-8")
            for tag in re.findall(r'<(?:script|link)[^>]+(?:src|href)="([^"]+)"', text):
                self.assertFalse(tag.startswith(("http://", "https://", "//")),
                                 f"{path.name} loads {tag} from a CDN")

    def test_external_content_links_are_present_and_safe(self):
        text = (SITE / "sources.html").read_text(encoding="utf-8")
        self.assertIn("statsapi.mlb.com", text)
        for m in re.findall(r'<a href="(https?://[^"]+)"', text):
            self.assertIn("rotogrinders", m) if "rotogrinders" in m else None
        self.assertIn('rel="noopener noreferrer"', text)

    def test_the_dashboard_reports_the_real_headline_numbers(self):
        text = (SITE / "index.html").read_text(encoding="utf-8")
        self.assertIn("0.07", text, "the externally validated scoring delta must be stated")
        self.assertIn("confirmed_by_operator", text, "the L-02 caveat must be on the landing page")

    def test_the_findings_page_lists_every_registered_finding(self):
        from rgengy import findings
        text = (SITE / "findings.html").read_text(encoding="utf-8")
        for f in findings.FINDINGS:
            self.assertIn(f.id, text, f"{f.id} is missing from the site")

    def test_the_scoring_page_lists_every_table(self):
        from rgengy import scoring
        text = (SITE / "scoring.html").read_text(encoding="utf-8")
        for key in scoring.available():
            self.assertIn(key, text, f"{key} is missing from the site")

    def test_the_grid_page_marks_unobserved_schemas(self):
        text = (SITE / "grid.html").read_text(encoding="utf-8")
        self.assertIn("NOT transcribed", text, "IR-22 must be visible on the grid page")

    def test_the_sidebar_marks_the_current_page(self):
        text = (SITE / "sources.html").read_text(encoding="utf-8")
        self.assertIn('aria-current="page"', text)

    def test_jekyll_is_disabled(self):
        self.assertTrue((SITE / ".nojekyll").exists())


if __name__ == "__main__":
    unittest.main(verbosity=2)


class TestLinkIntegrity(unittest.TestCase):
    """Every internal link in the published site and in docs/ must resolve.

    A generated page full of links to files that do not exist looks identical to
    a working one until a reviewer clicks, so this is checked rather than eyeballed.
    """

    def _doc_links(self):
        for path in sorted(DOCS.glob("*.md")) + [pathlib.Path(helpers.REPO) / "README.md"]:
            if not path.exists():
                continue
            for m in re.finditer(r"\]\(([^)]+)\)", path.read_text(encoding="utf-8")):
                url = m.group(1).split("#")[0]
                if not url or url.startswith(("http://", "https://", "mailto:")):
                    continue
                yield path, url

    def _site_links(self):
        for path in sorted(SITE.glob("*.html")):
            for m in re.finditer(r'href="([^"]+)"', path.read_text(encoding="utf-8")):
                url = m.group(1).split("#")[0]
                if not url or url.startswith(("http://", "https://", "mailto:", "#", "data:")):
                    continue
                yield path, url

    def test_no_broken_relative_links_in_the_docs(self):
        bad = [f"{p.name}: {u}" for p, u in self._doc_links()
               if not (p.parent / u).resolve().exists()]
        self.assertEqual(bad, [])

    def test_no_broken_internal_links_in_the_site(self):
        bad = sorted({f"{p.name}: {u}" for p, u in self._site_links()
                      if not (p.parent / u).resolve().exists()})
        self.assertEqual(bad, [])

    def test_a_markdown_link_with_a_fragment_becomes_an_html_link(self):
        """Regression: `09-irregularities.md#ir03` does not end with `.md`, so the
        suffix was never rewritten and the site linked to a nonexistent file."""
        out = build_site._inline("[IR-03](09-irregularities.md#ir03)")
        self.assertIn('href="09-irregularities.html#ir03"', out)

    def test_a_plain_markdown_link_still_becomes_html(self):
        self.assertIn('href="02-data-sources.html"',
                      build_site._inline("[src](02-data-sources.md)"))

    def test_every_sidebar_target_exists(self):
        index = (SITE / "index.html").read_text(encoding="utf-8")
        targets = re.findall(r'<a href="([^"#]+\.html)"', index)
        self.assertTrue(targets)
        for t in set(targets):
            self.assertTrue((SITE / t).exists(), t)

    def test_official_source_links_are_reachable_urls(self):
        """Not a network check - a shape check: every external href must be an
        absolute http(s) URL with a host, so a reviewer can click through."""
        for path, url in self._site_links():
            continue
        text = (SITE / "sources.html").read_text(encoding="utf-8")
        externals = re.findall(r'href="(https?://[^"]+)"', text)
        self.assertTrue(externals)
        for u in externals:
            self.assertRegex(u, r"^https?://[^/\s]+\S*$")


class TestReadmeAccuracy(unittest.TestCase):
    """The README's headline numbers are generated between sentinels.

    Stating them in hand-written prose creates an unstable loop: the test that
    checks the count is itself a test, so correcting the number changes it again.
    These tests assert the block is present, generated, and consistent with the
    registries - so a hand edit is caught instead of silently drifting.
    """

    def setUp(self):
        self.text = (pathlib.Path(helpers.REPO) / "README.md").read_text(encoding="utf-8")

    def test_the_stats_block_is_delimited_by_sentinels(self):
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        self.assertIn(build_docs.STATS_START, self.text)
        self.assertIn(build_docs.STATS_END, self.text)
        self.assertLess(self.text.index(build_docs.STATS_START),
                        self.text.index(build_docs.STATS_END))

    def test_the_block_is_regenerable_and_matches_what_is_committed(self):
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        data = build_docs.build_site_data()
        data["tests"] = build_docs._test_inventory()
        regenerated = build_docs.update_readme(data)
        self.assertIsNotNone(regenerated, "the sentinels are missing from README.md")
        self.assertEqual(regenerated, self.text,
                         "README.md was edited by hand inside the generated block, "
                         "or the registries changed without regenerating")

    def test_the_counts_in_the_block_match_the_registries(self):
        from rgengy import findings, scoring, sources
        self.assertIn(f"**{len(sources.ENDPOINTS)} registered endpoints**", self.text)
        self.assertIn(f"**{len(scoring.available())} scoring tables**", self.text)
        self.assertIn(f"**{len(findings.FINDINGS)} findings on the register**", self.text)

    def test_no_hand_written_test_count_remains_anywhere(self):
        """A bare count in prose is exactly what the sentinels exist to prevent."""
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        outside = self.text
        a = outside.index(build_docs.STATS_START)
        b = outside.index(build_docs.STATS_END) + len(build_docs.STATS_END)
        outside = outside[:a] + outside[b:]
        self.assertNotRegex(outside, r"\b\d{3} tests\b")
        index = (DOCS / "00-index.md").read_text(encoding="utf-8")
        self.assertNotRegex(index, r"\b\d{3} tests\b")

    def test_committed_output_carries_no_wall_clock_timestamp(self):
        """A live timestamp in committed output makes `--check` fail forever.

        This bit twice: first in the doc banner, then again inside the sources
        summary nested in site/data/rgengy.json, which `verification_summary()`
        stamps at call time.  Every timestamp in the committed artefacts must equal
        the reproducible build stamp.
        """
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        stamp = build_docs.generated_at()
        blob = (pathlib.Path(helpers.REPO) / "site" / "data" / "rgengy.json").read_text()
        stamps = set(re.findall(r"\"generated_at\": \"([^\"]+)\"", blob))
        self.assertEqual(stamps, {stamp},
                         "site/data/rgengy.json contains a timestamp that is not the "
                         f"reproducible build stamp {stamp!r}: {sorted(stamps - {stamp})}")

    def test_the_build_stamp_is_reproducible_without_any_environment(self):
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        saved = os.environ.pop("SOURCE_DATE_EPOCH", None)
        try:
            first = build_docs.generated_at()
            time.sleep(1.05)
            self.assertEqual(first, build_docs.generated_at(),
                             "the build stamp moved without SOURCE_DATE_EPOCH being set")
            self.assertTrue(first.startswith(build_docs.AUDIT_DATE))
        finally:
            if saved is not None:
                os.environ["SOURCE_DATE_EPOCH"] = saved

    def test_the_pages_workflow_does_not_inject_a_build_stamp(self):
        """Setting SOURCE_DATE_EPOCH in CI breaks --check; see generated_at()."""
        wf = (pathlib.Path(helpers.REPO) / ".github" / "workflows" / "pages.yml").read_text()
        self.assertNotIn("SOURCE_DATE_EPOCH=$(", wf)
        self.assertNotRegex(wf, r"echo \"SOURCE_DATE_EPOCH")

    def test_the_method_docs_test_table_is_generated_and_current(self):
        """docs/01's per-module counts were hand-written and drifted (said 399/16).

        They now live between sentinels and are rendered from the same inventory as
        the dashboard, so a hand edit is caught rather than silently going stale.
        """
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        method = (DOCS / "01-method.md").read_text(encoding="utf-8")
        self.assertIn(build_docs.METHOD_START, method)
        data = build_docs.build_site_data()
        data["tests"] = build_docs._test_inventory()
        regenerated = build_docs.update_method(data)
        self.assertIsNotNone(regenerated)
        self.assertEqual(regenerated, method,
                         "docs/01-method.md was edited inside its generated test block, "
                         "or the suite changed without regenerating")

    def test_every_test_module_has_a_written_description(self):
        sys.path.insert(0, str(pathlib.Path(helpers.REPO) / "scripts"))
        import build_docs
        modules = {t["module"] for t in build_docs._test_inventory()}
        described = set(build_docs.TEST_COVER)
        self.assertEqual(modules - described, set(),
                         "test modules with no 'covers' description in build_docs.TEST_COVER")

    def test_the_documented_pages_all_exist(self):
        for m in re.finditer(r"\]\((docs/[^)#]+\.md)\)", self.text):
            self.assertTrue((pathlib.Path(helpers.REPO) / m.group(1)).exists(), m.group(1))

    def test_the_readme_links_to_the_published_site(self):
        self.assertIn("buffedlizard55-lab.github.io/RGENGY", self.text)


